INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (1, 1, N'Manager on Duty', 1, 1)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (2, 1, N'General Manager', 1, 2)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (3, 2, N'Parking Lot', 1, 1)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (4, 2, N'Signage', 1, 2)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (5, 2, N'Building Exterior', 1, 3)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (6, 2, N'Back Door', 1, 4)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (7, 2, N'Garbage Enclosure', 1, 5)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (8, 2, N'General Cleanliness of Exterior', 1, 6)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (9, 2, N'Landscaping', 1, 7)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (10, 2, N'Sidewalks and Walkways', 1, 8)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (11, 2, N'Patio', 1, 9)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (12, 2, N'Front Door', 1, 10)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (13, 3, N'Lobby', 1, 1)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (14, 3, N'Furniture', 1, 2)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (15, 3, N'Floors', 1, 3)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (16, 3, N'Lighting', 1, 4)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (17, 3, N'Cleanliness', 1, 5)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (18, 3, N'Employee Uniforms', 1, 6)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (19, 3, N'Equipment', 1, 7)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (20, 3, N'Bar/Lounge', 1, 8)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (21, 3, N'Restrooms', 1, 9)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (22, 3, N'Menus', 1, 10)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (23, 3, N'Marketing Materials', 1, 11)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (24, 3, N'Back Bar areas', 1, 12)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (25, 3, N'Pre-Shift Meetings', 1, 13)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (26, 4, N'Equipment', 1, 1)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (27, 4, N'Line Check', 1, 2)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (28, 4, N'Food Quality Prep/Online', 1, 3)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (29, 4, N'Main Cooler', 1, 4)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (30, 4, N'Main Freezer', 1, 5)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (31, 4, N'On-Line Refrigeration', 1, 6)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (32, 4, N'Food Quality Pass through', 1, 7)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (33, 4, N'Temperature Checks', 1, 8)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (34, 4, N'Shelf Life Standards followed', 1, 9)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (35, 4, N'Uniforms', 1, 10)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (36, 5, N'Quality', 1, 1)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (37, 5, N'Service', 1, 2)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (38, 5, N'Management Presence', 1, 3)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (39, 5, N'Energy of Staff', 1, 4)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (40, 5, N'Product Knowledge of Staff', 1, 5)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (41, 5, N'Atmosphere', 1, 6)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (42, 5, N'Empathica Results', 1, 7)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (43, 5, N'Communication', 1, 8)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (44, 5, N'Salesmanship', 1, 9)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (45, 5, N'Staffing Levels', 1, 10)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (46, 5, N'Food Quality overall', 1, 11)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (47, 5, N'Coaching During Service', 1, 12)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (48, 5, N'Drive-in Service', 1, 13)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (49, 5, N'Take-out Service', 1, 14)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (50, 5, N'New Hires Training', 1, 15)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (51, 5, N'Red Book utilized to max', 1, 16)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (52, 5, N'Health & Safety', 1, 17)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (53, 5, N'Food and Labour Cost', 1, 18)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (54, 5, N'Ops Review Readiness', 1, 19)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (55, 5, N'Financial Discussion', 1, 20)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (56, 5, N'Local Store Marketing', 1, 21)
INSERT INTO [dbo].[Question] ([QuestionID], [SectionID], [QuestionName], [Active], [QuestionOrder]) VALUES (57, 5, N'Brand Standards Followed', 1, 22)