//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checklist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Sections = new HashSet<Section>();
            this.SiteVisits = new HashSet<SiteVisit>();
        }
    
        public int FormID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Concept { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<SiteVisit> SiteVisits { get; set; }
    }
}
