//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checklist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int QuestionID { get; set; }
        public int SectionID { get; set; }
        public string QuestionName { get; set; }
        public bool Active { get; set; }
        public int QuestionOrder { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Section Section { get; set; }
    }
}
